# -*- coding: utf-8 -*-
"""NLP FINAL PROJECT - ArXiv ID FOR Top Papers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jJGtFecec-sseZKi3hX9GfOuIACUEu6
"""

import pandas as pd

top_papers_df = pd.read_csv('miscellaneous/top_500_arxiv_papers.csv')

#print(top_papers_df)

top_papers_df.loc[top_papers_df['doi'].notnull() == True]

extractable_top_papers = top_papers_df.loc[top_papers_df['doi'].notnull() == True]

#print(extractable_top_papers)

#print(extractable_top_papers['doi'])

test_ids = extractable_top_papers['doi'].apply(lambda x: x.split('/')[-1]).to_list()
next_test_ids = [s.split('.') for s in test_ids if len(s.split('.')) == 3 and s.split('.')[0].lower() == 'arxiv']
final_ids = ['.'.join(path[1:]) for path in next_test_ids]

#print(len(final_ids), final_ids)

with open('miscellaneous/cited_arxiv_ids.txt', 'w') as f:
    for item in final_ids:
        f.write(f"{item}\n")
